// ACTIONS && MUTATIONS
export const ADD_LOADED_FILE = 'ADD_LOADED_FILE';
export const ADD_FILE_TO_QUEUE = 'ADD_FILE_TO_QUEUE';
export const CLEAR_LOADED_FILES = 'CLEAR_LOADED_FILES';
export const REMOVE_FILE = 'REMOVE_FILE';
export const REMOVE_FILES_FROM_STAGING = 'REMOVE_FILES_FROM_STAGING';
export const REMOVE_STAGING_FILES = 'REMOVE_STAGING_FILES';
export const SEND_FILES = 'SEND_FILES';
export const MOVE_FILES_TO_STAGING = 'MOVE_FILES_TO_STAGING';
export const SET_LOADING = 'SET_LOADING';
export const MOVE_STAGING_TO_QUEUE = 'MOVE_STAGING_TO_QUEUE';
export const CHECK_QUEUE = 'CHECK_QUEUE';

// GETTERS
export const GET_LOADED_FILES = 'GET_LOADED_FILES';
export const GET_STAGING_FILES = 'GET_STAGING_FILES';
export const GET_FILES_IN_QUEUE = 'GET_FILES_IN_QUEUE';
export const GET_LOADING = 'GET_LOADING';
